name = "jads"
type = "javascript"
account_id = "6a041dfe24d207d6638700bb76b02118"
compatibility_date = "2024-09-16"

[site]
bucket = "./dist" # or your build directory
entry-point = "workers-site"

[build]
pages_build_output_dir = "./dist"  